# Generated by Django 4.2 on 2023-04-10 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='link',
            field=models.URLField(default='None', max_length=300),
        ),
    ]
